### ISSUE TITLE
[Idea] Dye everything more than just armor?

### ISSUE THREAD

**Issue by ardissaps** [Fourmisain/DyeAllTheThings#2]
It can us from installing many block mod that can cause long loading time etc. Would be efficient in mods list if we can dye every item to all available dye (brick, stone, coble etc)! Isn't that cool, yes? :)

**Comment by Fourmisain** [comment]
Due to the way blocks in Minecraft work you cannot simply dye them and make them render in their colors.
There's a long technical explanation behind it, but if it were that simple, there'd already be multiple mods doing it.

The closest thing that currently exists is [Mo' Colors](https://www.curseforge.com/minecraft/mc-mods/mo-colors) (which I highly recommend you use!) and even that doesn't actually color the original blocks but replaces them with new ones which are colorable.
